product-name: pivotal-telemetry-om
product-version: 2.2.0-build.3
product-properties:
  .properties.api_key:
    value:
      secret: no-op-test-key
  .properties.audit_mode:
    value: false
  .properties.collector_cron_schedule:
    value: random
  .properties.endpoint:
    value: https://telemetry.pivotal.io
  .properties.env_type:
    value: sandbox
  .properties.eula_acceptance:
    value:
      - agree
  .properties.flush_interval:
    value: 3600
  .properties.opsmanager_insecure_skip_tls_verify:
    value: true
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.data_collection_multi_select_options:
    value:
      - operational_data
      - ceip_data
network-properties:
  network:
    name: deployment
  other_availability_zones:
    - name: ((availability_zones.0))
  singleton_availability_zone:
    name: ((availability_zones.0))
resource-config:
  telemetry-centralizer:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    internet_connected: true
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
syslog-properties:
  enabled: false
  forward_debug_logs: false
  tls_enabled: false
  transport_protocol: tcp